sudo: required
services:
  - docker
before_install:
  - docker build -t tagarwal12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tagarwal12/react-test npm test

after_success:
  - docker build -t tagarwal12/multi-client -f ./client
  - docker build -t tagarwal12/multi-nginx -f ./nginx
  - docker build -t tagarwal12/multi-server -f ./server
  - docker build -t tagarwal12/multi-worker -f ./worker
# Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
# Take these images n push them to docker hub
  - docker push tagarwal12/multi-client
  - docker push tagarwal12/multi-nginx
  - docker push tagarwal12/multi-server
  - docker push tagarwal12/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'ap-south-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-ap-south-1-129879713922'
    bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  

